### ISSUE TITLE
Multiple authors per post not showing on the front end.

### ISSUE THREAD

**Issue by robindevitt** [humanmade/authorship#107]
While working on issue https://github.com/humanmade/product-dev/issues/993 I identified that posts with multiple authors were not showing the multiple authors on the front end, only the original author.

#### Steps to reproduce
1. Login to the site.
2. Ensure Authorship is enabled.
3. Create  or Navigate to a post and assign multiple authors.
4. Publish / Update the post.
5. View the post on the front end and you should only see a single author.

#### Expected behavior
When a post has multiple authors assigned and viewing the post on the front end you should see all the assigned authors.

#### Screenshots
![Screenshot 2022-08-16 at 10.25.01.png](https://images.zenhubusercontent.com/615d863972ceea502ec6a54f/a4ae490b-e279-4ebc-903c-053f3f3845e9)
![Screenshot 2022-08-16 at 10.25.40.png](https://images.zenhubusercontent.com/615d863972ceea502ec6a54f/59ec22c1-4b08-4d6d-b250-d492522db7c5)

#### Additional info
- Theme : Twenty Twenty-Two & Twenty Twenty-One
- Browser: Chrome Version 104.0.5112.79 (Official Build) (x86_64)
- OS : macOS Big Sur Version 11.6

**Comment by roborourke** [comment]
Does this plugin not have a specific function to output multiple authors? There might not be an issue here

**Comment by robindevitt** [comment]
Perfect, I wasn't 100% sure that was the case but going on the docs there is a section for **Template Functions**:
> The following template functions are available for use in your theme to fetch the attributed author(s) of a post:

Link - https://docs.altis-dxp.com/cms/authorship/#template-functions

Closing issue.
