### ISSUE TITLE
Replace post type supports checks with a filterable function

### ISSUE THREAD

**Issue by johnbillion** [humanmade/authorship#48]
The ability to assign attributed authors to a post is directly connected to whether the post type supports `author`. These checks should be replaced with calls to a function which encapsulates this check and a filter on its return value, so the feature can be enabled and disabled for all post types without necessarily affecting the post type support.

Maybe even check for a custom post type support of `authorship` too.

**Comment by johnbillion** [comment]
@shadyvb Can you open a follow-up issue with details of the problem you saw with the attachments query?

**Comment by shadyvb** [comment]
Sure, I'm not exactly sure if these are directly caused by the plugin or not though, but I'll log an issue to investigate.
