### ISSUE TITLE
Add info re initial funding of the plugin

### ISSUE THREAD

**Issue by yumito** [humanmade/authorship#79]
**Description:**
We need to add details on the initial sponsorship of the plugin in the plugin header, alongside the information on the author of the plugin, so that this information may be visible in the code and in the WP admin area.

**Acceptance criteria:**
1. as an engineer when I look at the plugin header I can see the information `Initial version sponsored by Siemens` alongside the information on who is the author of Authorship
2. as a user in the WP admin area when browsing the installed plugins i want to see `Initial version sponsored by Siemens` alongside the information on who is the author of Authorship

**Comment by shadyvb** [comment]
This is how it'll look like:

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/451892/119491676-7c01cb80-bd5e-11eb-82e7-a703bb6f5fdf.png">
